### ISSUE TITLE
Branch called "start" not found

### ISSUE THREAD

**Issue by timothydempsey** [planetoftheweb/angulardata#1]
Hi Ray,

Love the courses at Lynda, but this video on" Installing the template" references a branch called Start that doesn't seem to exist. 

I grabbed the Master, just thought you should know.

Keep up the great work.
Tim

**Comment by planetoftheweb** [comment]
Thanks for the heads up. This is an update to the course, so it looks like I didn't move the start branch since I was mostly updating the later chapters. The original course is https://github.com/planetoftheweb/angulardata_old, so I'll move the branch from there...good find.

**Comment by planetoftheweb** [comment]
Added start branch back into project
