### ISSUE TITLE
gulp does not run

### ISSUE THREAD

**Issue by lkimsey** [planetoftheweb/angulardata#11]
Linux pad-lawrencekimsey-com 5.0.9-301.fc30.x86_64 #1 SMP Tue Apr 23 23:57:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

[lk@pad-lawrencekimsey-com angulardata]$ node -v
v10.16.0
[lk@pad-lawrencekimsey-com angulardata]$ npm -v
6.9.0
[lk@pad-lawrencekimsey-com angulardata]$ git --version
git version 2.21.0
[lk@pad-lawrencekimsey-com angulardata]$ 

[lk@pad-lawrencekimsey-com angulardata]$ gulp
bash: gulp: command not found...

**Comment by planetoftheweb** [comment]
Thanks for the note...just finished a course, so I'm going to figure out why this isn't working.

**Comment by planetoftheweb** [comment]
Unfortunately, this project is a bit old and needs updating. I don't have a lot of info about how . you're running things.
