### ISSUE TITLE
gulp error

### ISSUE THREAD

**Issue by goscha01** [planetoftheweb/angulardata#12]
The command $gulp throws this error:
$ gulp   assert.js:350
 throw err;  
 ^                                                                                                                                                                                                 AssertionError [ERR_ASSERTION]: Task function must be specified

**Comment by planetoftheweb** [comment]
That error means that you don't have a task in your project, which sort of doesn't make sense. I'm assuming you're not putting the dollar sign in the command. This project is a bit old though.
