### ISSUE TITLE
$firebaseSimpleLogin deprecated

### ISSUE THREAD

**Issue by j-gibweb** [planetoftheweb/angulardata#2]
$firebaseSimpleLogin is deprecated in angularfire, causes Unknown provider error.

 Error: [$injector:unpr] http://errors.angularjs.org/1.3.0-beta.19/$injector/unpr?p0=NaNirebaseSimpleLoginProvider%20%3C-%20%24firebaseSimpleLogin

change $firebaseSimpleLogin to $firebaseAuth

my working example code as of 01-16-2015

  var ref = new Firebase('https://your-app.firebaseio.com/');

 $scope.login = function() {
    ref.authWithPassword({
      email: $scope.user.email,
      password: $scope.user.password
    }, function(error, authData) {
      if (error) {
        console.log("Login Failed!", error);
      } else {
        console.log("Authenticated successfully with payload:", authData);
        $location.path('/meetings');
        $scope.$apply();
      }
    });
  }; //login

 $scope.$apply(); is needed due to change in $location.path() outside of angular framework

**Comment by planetoftheweb** [comment]
Hey
Thanks for the note. It's sort of deprecated. I'm recording fixes within the next couple of weeks. In the meantime, the brach called authworking has the code with the new SimpleLogin working.
