### ISSUE TITLE
Problem in Authentication.login(user)

### ISSUE THREAD

**Issue by imieites** [planetoftheweb/angulardata#3]
Hello,

In the login function of the Authentication service, I see the 'user' variable passed as parameter only contains the email and password of the user we want to login. But on the 1st line of the function I see that we're trying to set userRef by using 'user.uid'. The problem I see in my test is that user.uid is undefined at this point. Am I missing something?

```
login : function(user) {
      var userRef = new Firebase(FIREBASE_URL + '/users/' + user.uid);
      var userObj = $firebase(userRef).$asObject();
...
```
A solution I found is authenticating first (I'm using firebaseAuth instead of SimpleLogin), and the promise of that returns the user data we need, including the uid, so now it can be used. Something like this...

```
        login : function(user) {

            return authObj.$authWithPassword({
                email: user.email,
                password: user.password
            })
            .then(function(authData){ 
                console.log('authentication.js: logged in user '+ authData.uid);

                var userRef = new Firebase(FIREBASE_URL + 'users/' + authData.uid);
                var userObj = $firebase(userRef).$asObject();

                userObj.$loaded().then(function() {
                    $rootScope.currentUser = userObj;
                });

                $rootScope.$broadcast('$firebaseAuth:authWithPassword',authData); // avisa al scope

              return authData;
          });
```

**Comment by planetoftheweb** [comment]
Hi there,

Yes. Unfortunately, this course was built with the old version of SimpleLogin. The changes to the new service are quite dramatic.

Thankfully, I just finished re-recording the course for the new authentication service. It will take a while before it goes live, but you can check out all of the code at this URL

http://github.com/planetoftheweb/angulardatau

To answer your specific questions, you can use events to make sure that the authentication process has completed. You can use $getAuth or $onAuth (https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-users-and-authentication-getauth), but there's a better way that I show in the new video, which is to handle pre-verification through your routes. 

```
    when('/meetings', {
      templateUrl: 'views/meetings.html',
      controller: 'MeetingsController',
      resolve : {
        currentAuth: function(Authentication) {
          return Authentication.requireAuth();
        }
      }
    }).
```

You can catch potential authentication errors like this:

```
myApp.run(['$rootScope', '$location', function($rootScope, $location) {
  $rootScope.$on('$routeChangeError',
  function(event, next, previous, error) {
    if(error === 'AUTH_REQUIRED') {
      $rootScope.message='Sorry, you must log in to access that page';
      $location.path('/login');
    }
  });
}]);
```

Here's my new app.js file:
https://github.com/planetoftheweb/angulardatau/blob/master/builds/development/js/app.js

And my new Authentication service
https://github.com/planetoftheweb/angulardatau/blob/master/builds/development/js/services/authentication.js

Hopefully that helps.
