### ISSUE TITLE
Can't register a new user

### ISSUE THREAD

**Issue by milleson** [planetoftheweb/angulardata#6]
error displayed when adding a new user: firebaseUsers.$set is not a function 

the code below is from authentication.js, lines 41 - 59 (see third from the end)

```
register: function(user) {
  return auth.$createUser({
    email: user.email,
    password: user.password
  }).then(function(regUser) {
    var ref = new Firebase(FIREBASE_URL+'users');
    var firebaseUsers = $firebaseObject(ref);     
```

from registrations 
  var userInfo = {
          date : Firebase.ServerValue.TIMESTAMP,
          regUser : regUser.uid,
          firstname: user.firstname,
          lastname : user.lastname,
          email: user.email
        }; //user info

```
    firebaseUsers.$set(regUser.uid, userInfo);
  }); //promise
}, //register
```

TypeError: firebaseUsers.$set is not a function
    at authentication.js:57
    at angular.js:14551
    at m.$get.m.$eval (angular.js:15830)
    at m.$get.m.$digest (angular.js:15641)
    at angular.js:15869
    at e (angular.js:5387)
    at angular.js:5659

I looked into the docs and there isn't a $set method in angularfire

**Comment by planetoftheweb** [comment]
This is a valid bug. I'm working on this right now.Thanks the input. The problem is I'm still using $set here where I should be using $add.

**Comment by planetoftheweb** [comment]
Fixed this. Thanks to Jerome. Looks like I missed switching one of the $save commands to an $add
